name: Upload Website

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build with Zola
        uses: kytta/zola-build-pages@v1
        with:
          zola-version: "0.17.2"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: public
          path: ./public/
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: public
          path: ./public/
      - run: aws s3 sync --size-only --delete --region eu-central-1 public s3://spiss.dev/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
